require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop) do |task|
  task.patterns = ['libraries','providers','resources','test/integration/default/serverspec']
  task.options = ['--display-cop-names']
end
